#!/bin/sh

mkdir /var/db/mysql
cp /mnt/ports/hosts /etc/hosts

# install apache 1.3.33_1
cd /mnt/ports/apache-1.3.33_1/
pkg_add apache-1.3.33_1.tbz

# install ccrypt 1.7
cd /mnt/ports/ccrypt-1.7/
pkg_add ccrypt-1.7.tbz

# install clamav 0.83
cd /mnt/ports/clamav-0.83/
pkg_add clamav-0.83.tbz

# install expect 5.42.1
cd /mnt/ports/expect-5.42.1/
pkg_add expect-5.42.1.tbz

# install mysql server 4.0.23a
cd /mnt/ports/mysql-server-4.0.24/
pkg_add mysql-server-4.0.23a.tbz

# install php4
cd /mnt/ports/php4-4.3.10_2/
pkg_add php4-4.3.10_2.tbz

# install php4 extensions
cd /mnt/ports/php4-extensions-1.0/
pkg_add php4-extensions-1.0.tbz

# install samba 3.0.11,1
cd /mnt/ports/samba-3.0.11,1/
pkg_add samba-3.0.11,1.tbz

# install smartmontools 5.32
cd /mnt/ports/smartmontools-5.32/
pkg_add smartmontools-5.32.tbz

# install sudo 1.6.8.7
cd /mnt/ports/sudo-1.6.8.7/
pkg_add sudo-1.6.8.7.tbz
